Repository personium/website, pull requests merged in 2020-03, with the labels that each got.

#8 CHORES: Add new event and fix wording for older event
  website/blog/2020-01-30-Own-Your-Data-Pilot.md
  website/blog/2020-02-20-Fujitsu-100-Persons-Kaigi.md
Labels: documentation

#12 UPDATES: Add news to blog
  website/blog/2020-03-02-CEPS-Workshop-Announcement.md
  website/blog/2020-03-03-EMWA-Paper.md
  website/blog/2020-03-03-MyData-Operator-Whitepaper.md
Labels: documentation

#13 UPDATES: Add configuration steps
  README.md
Labels: documentation

#15 Unify sidebars categories
  src/README.md
  website/i18n/en.json
  website/i18n/ja.json
  website/sidebars.json
Labels: enhancement

#18 CHORES: Organize API reference side bar
  website/blog/2020-02-12-MyData-Case-Library.md
  website/sidebars.json
Labels: documentation

#21 CHORES: Update API Reference side bar
  website/sidebars.json
Labels: enhancement

#19 Add cell level api's sidebars
  website/sidebars.json
Labels: enhancement

#20 Add common sidebars
  website/sidebars.json
Labels: enhancement

#22 CHORES: Updates missing commits
  website/static/en/demo/home-app/index.html
  website/static/en/index.html
  website/static/ja/demo/home-app/index.html
  website/static/ja/index.html
Labels: documentation

#30 fix API ref: Explanation of event code "PL-BI-1002" is missing in Box Install page
  src/apiref/302_Box_Installation.md
  website/translated_docs/ja/apiref/302_Box_Installation.md
Labels: documentation

#32 Fix request body in $batch
  src/apiref/368_Entity_Bulk_Operations.md
  website/translated_docs/ja/apiref/368_Entity_Bulk_Operations.md
  website/translated_docs/ja/version-1.7.21/apiref/368_Entity_Bulk_Operations.md
  website/versioned_docs/version-1.7.21/apiref/368_Entity_Bulk_Operations.md
Labels: bug

#33 CHORES: Update community list
  website/static/en/index.html
  website/static/ja/index.html
Labels: documentation

#34 CHORES: Add summaries for MyData Spring Community Meeting Online
  website/blog/2020-03-23-AmsterdamCommunityMeeting.md
Labels: documentation

#36 CHORES: Add bi-weekly meeting announcement for CEPS
  website/blog/2020-03-24-CEPS-Bi-weekly-Meeting-Announcement.md
Labels: documentation
